# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f0220f45fe6f2251e073a22007fe9fca"
name = "Product-Management-LPC"
handle = "product-management-lpc"
application_url = "https://bind-wash-running-promised.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "lpc-product-creation.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_inventory,read_locations,read_orders,read_products,read_publications,write_fulfillments,write_inventory,write_products, write_publications"

[auth]
redirect_urls = [
  "https://bind-wash-running-promised.trycloudflare.com/auth/callback",
  "https://bind-wash-running-promised.trycloudflare.com/auth/shopify/callback",
  "https://bind-wash-running-promised.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
