# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9b5b06e5fa81de95c5e6b0467701f0d"  # Your new development app's client ID
name = "LPC Product Management - Dev"  # Updated name to indicate development version
handle = "product-management-lpc-dev"  # Added -dev to distinguish from production
application_url = "https://lpc-product-management-development.up.railway.app"  # Your Railway development URL
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lpc-product-creation.myshopify.com"  # Your development store
include_config_on_deploy = true

[access_scopes]
# Keeping the same scopes as production to ensure feature parity
scopes = "read_fulfillments,read_inventory,read_locations,read_orders,read_products,read_publications,write_fulfillments,write_inventory,write_products,write_publications"

[auth]
redirect_urls = [
  "https://lpc-product-management-development.up.railway.app/auth/callback",
  "https://lpc-product-management-development.up.railway.app/auth/shopify/callback",
  "https://lpc-product-management-development.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false