# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df58a5b13484ffc9b63eb3e420dca6f9"
name = "LPC Product Management - Dev"
handle = "lpc-product-management-dev-1"
application_url = "https://democratic-focus-census-deutschland.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lpc-product-management-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_inventory,read_locations,read_orders,read_products,read_publications,write_fulfillments,write_inventory,write_products,write_publications"

[auth]
redirect_urls = [
  "https://democratic-focus-census-deutschland.trycloudflare.com/auth/callback",
  "https://democratic-focus-census-deutschland.trycloudflare.com/auth/shopify/callback",
  "https://democratic-focus-census-deutschland.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
