export const initialFormState = {
  selectedCollection: "",
  selectedOfferingType: "",
  limitedEditionQuantity: "",
  selectedLeatherColor1: "",
  selectedLeatherColor2: "",
  selectedStitchingColor: "",
  selectedEmbroideryColor: "",
  selectedEmbroideryColors: {},
  selectedFont: "",
  selectedShapes: {},
  selectedStyles: {},
  weights: {},
  qClassicLeathers: {},
  matchingAmannNumber: "",
  matchingIsacordNumber: "",
  shapeIsacordNumbers: {},
};