export const initialFormState = {
  selectedCollection: "",
  selectedOfferingType: "",
  limitedEditionQuantity: "",
  selectedLeatherColor1: "",
  selectedLeatherColor2: "",
  selectedStitchingColors: [],
  matchingAmannNumbers: [],
  selectedEmbroideryColor: {},
  selectedEmbroideryColors: {},
  selectedFont: "",
  selectedShapes: {},
  selectedStyle: "", 
  selectedStyles: {}, 
  weights: {},
  qClassicLeathers: {},
  matchingIsacordNumber: "",
  shapeIsacordNumbers: {},
};