// app/components/ShapeSelector/fields/ShapeImageCapture.jsx
//
// Renders the per-shape image dropzones inside a shape row. Capture only — no Drive upload happens
// here. Files are stashed in the parent's `pendingVariantImages` state (keyed by `shapeValue` +
// view label) and pushed to Google Drive at submit time, after `generateProductData` has produced
// the real `variant.sku` for each shape. This mirrors the way the existing reference/group image
// flow defers its upload until submit (see `handleGroupImageDriveUpload` in
// `app/routes/app.createProducts.jsx`).
//
// Why dropzones live here instead of in the Preview section:
//  * Non-representative mallet sibling rows (`isActive === false`) are filtered out of the input
//    UI entirely, so a dropzone-per-shape-row naturally enforces "image only for representative
//    Mallet" without an extra rule. The hidden sibling variants generated by
//    `expandSelectionsBySizingGuideGroup` are intentionally left without images — Karl uses the
//    representative SKU in the Drive filename to route them by hand.
//  * Drivers / Fairways / Hybrids get an optional `Back` view (alongside `Front`).

import React, { useCallback, useMemo } from "react";
import { InlineStack, BlockStack, Text, Box } from "@shopify/polaris";
import ImageDropZone from "../../ImageDropZone";
import { getVariantViewLabels } from "../../../lib/utils/shapeUtils";

const VIEW_BOX_WIDTH = "96px";

const ShapeImageCapture = ({
  shape,
  formState,
  pendingVariantImages,
  onSetPendingImage,
}) => {
  const shapeState = formState?.allShapes?.[shape.value];
  const isSelected = Boolean(shapeState?.isSelected);

  const viewLabels = useMemo(() => getVariantViewLabels(shape), [shape]);
  const pendingForShape = pendingVariantImages?.[shape.value];

  const handleDrop = useCallback(
    (label) => (files) => {
      if (!files || files.length === 0) return;
      onSetPendingImage?.(shape.value, label, files[0]);
    },
    [shape.value, onSetPendingImage]
  );

  if (!isSelected || viewLabels.length === 0) {
    return null;
  }

  return (
    <InlineStack gap="200" align="start" wrap={false}>
      {viewLabels.map((label) => {
        const previewUrl = pendingForShape?.[label]?.previewUrl ?? null;
        return (
          <BlockStack key={`${shape.value}-${label}`} gap="100" align="start">
            <Box width={VIEW_BOX_WIDTH}>
              <ImageDropZone
                size="small"
                label={label}
                customWidth={VIEW_BOX_WIDTH}
                customHeight="96px"
                uploadedImageUrl={previewUrl}
                accept="image/jpeg,image/jpg,image/png,.jpg,.jpeg,.png"
                onDrop={handleDrop(label)}
              />
            </Box>
            <Box width={VIEW_BOX_WIDTH}>
              <Text variant="bodySm" tone="subdued" alignment="center">
                {label}
              </Text>
            </Box>
          </BlockStack>
        );
      })}
    </InlineStack>
  );
};

export default React.memo(ShapeImageCapture);
